modLoader="javafml"
loaderVersion="[10,)"
license="CC-BY-NC-SA-4.0"
[[mods]]
modId="astral_repository"
version="${version}"
displayName="Astral Repository"
authors="CappleApple"
description='''A crystal network that discovers workshop storage, moves resources, and plans crafting from the products in your recipe library.'''
[[dependencies.astral_repository]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.astral_repository]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.astral_repository]]
modId="patchouli"
type="optional"
versionRange="[1.21.1-93,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="astral_repository.mixins.json"


[[dependencies.astral_repository]]
modId="curios"
type="optional"
versionRange="[9.5.1,)"
ordering="AFTER"
side="BOTH"

