modLoader="javafml"
loaderVersion="[47,)"
license="CC-BY-NC-SA-4.0"
[[mods]]
modId="astral_repository"
version="${version}"
displayName="Astral Repository"
authors="CappleApple"
description='''A crystal network that discovers workshop storage, moves resources, and plans crafting from the products in your recipe library.'''
[[dependencies.astral_repository]]
modId="forge"
mandatory=true
versionRange="[47.4.23,)"
ordering="NONE"
side="BOTH"
[[dependencies.astral_repository]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.astral_repository]]
modId="patchouli"
mandatory=false
versionRange="[1.20.1-84.1,)"
ordering="AFTER"
side="BOTH"




[[dependencies.astral_repository]]
modId="curios"
mandatory=false
versionRange="[5.14.1,)"
ordering="AFTER"
side="BOTH"
