package com.cappleapple.astralrepository.platform.capabilities;
import java.util.*;import net.minecraft.world.item.ItemStack;import net.fabricmc.fabric.api.transfer.v1.storage.*;import net.fabricmc.fabric.api.transfer.v1.item.ItemVariant;import net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant;import net.fabricmc.fabric.api.transfer.v1.transaction.Transaction;import com.cappleapple.astralrepository.platform.fluids.FluidStack;import com.cappleapple.astralrepository.platform.fluids.capability.IFluidHandler;import com.cappleapple.astralrepository.platform.items.IItemHandler;import com.cappleapple.astralrepository.platform.energy.IEnergyStorage;
public final class FabricTransfer {
 public static Object identity(Object handler){if(handler instanceof ItemHandler item)return item.storage;if(handler instanceof FluidHandler fluid)return fluid.storage;if(handler instanceof EnergyHandler energy)return energy.storage;return handler;}
 static int cap(long amount){return (int)Math.min(Integer.MAX_VALUE,Math.max(0,amount));}
 static <T> List<StorageView<T>> views(Storage<T> storage){var out=new ArrayList<StorageView<T>>();storage.forEach(out::add);return out;}
 public static final class ItemHandler implements IItemHandler {
  private final Storage<ItemVariant> storage;public ItemHandler(Storage<ItemVariant> storage){this.storage=storage;}private List<StorageView<ItemVariant>> views(){return FabricTransfer.views(storage);}
  public int getSlots(){return storage instanceof SlottedStorage<?> slots?slots.getSlotCount():views().size()+1;}
  public ItemStack getStackInSlot(int slot){var views=views();return slot>=views.size()?ItemStack.EMPTY:views.get(slot).getResource().toStack(cap(views.get(slot).getAmount()));}
  public int getSlotLimit(int slot){var views=views();return slot>=views.size()?Integer.MAX_VALUE:cap(views.get(slot).getCapacity());}public boolean isItemValid(int slot,ItemStack stack){return storage.supportsInsertion();}
  public ItemStack insertItem(int slot,ItemStack stack,boolean simulate){if(stack.isEmpty())return stack;if(!(storage instanceof SlottedStorage<?>)){var all=views();int insertionSlot=all.size();var variant=ItemVariant.of(stack);for(int i=0;i<all.size();i++)if(all.get(i).isResourceBlank()||all.get(i).getResource().equals(variant)){insertionSlot=i;break;}if(slot!=insertionSlot)return stack;}Storage<ItemVariant> target=storage instanceof SlottedStorage<ItemVariant> slots?slots.getSlot(slot):storage;try(var tx=Transaction.openOuter()){long n=target.insert(ItemVariant.of(stack),stack.getCount(),tx);if(!simulate)tx.commit();return stack.copyWithCount(stack.getCount()-cap(n));}}
  public ItemStack extractItem(int slot,int amount,boolean simulate){var views=views();if(slot>=views.size()||amount<=0)return ItemStack.EMPTY;var view=views.get(slot);var variant=view.getResource();try(var tx=Transaction.openOuter()){long n=view.extract(variant,amount,tx);if(!simulate)tx.commit();return variant.toStack(cap(n));}}
 }
 public static final class FluidHandler implements IFluidHandler {
  private static final long DROPLETS_PER_MB=81;private final Storage<FluidVariant> storage;public FluidHandler(Storage<FluidVariant> storage){this.storage=storage;}
  public int getTanks(){return views(storage).size();}public FluidStack getFluidInTank(int tank){var view=views(storage).get(tank);return new FluidStack(view.getResource(),cap(view.getAmount()/DROPLETS_PER_MB));}public int getTankCapacity(int tank){return cap(views(storage).get(tank).getCapacity()/DROPLETS_PER_MB);}public boolean isFluidValid(int tank,FluidStack stack){return storage.supportsInsertion();}
  private int transfer(FluidStack stack,FluidAction action,boolean insert){if(stack.isEmpty())return 0;long requested=(long)stack.getAmount()*DROPLETS_PER_MB;long units;try(var tx=Transaction.openOuter()){long accepted=insert?storage.insert(stack.variant(),requested,tx):storage.extract(stack.variant(),requested,tx);units=accepted/DROPLETS_PER_MB;if(accepted%DROPLETS_PER_MB==0){if(action.execute())tx.commit();return cap(units);}}
   if(action.simulate()||units==0)return cap(units);try(var tx=Transaction.openOuter()){long exact=insert?storage.insert(stack.variant(),units*DROPLETS_PER_MB,tx):storage.extract(stack.variant(),units*DROPLETS_PER_MB,tx);if(exact!=units*DROPLETS_PER_MB)return 0;tx.commit();return cap(units);}}
  public int fill(FluidStack stack,FluidAction action){return transfer(stack,action,true);}public FluidStack drain(FluidStack stack,FluidAction action){return stack.copyWithAmount(transfer(stack,action,false));}public FluidStack drain(int amount,FluidAction action){for(var view:storage)if(!view.isResourceBlank()&&view.getAmount()>=DROPLETS_PER_MB)return drain(new FluidStack(view.getResource(),amount),action);return FluidStack.EMPTY;}
 }
 public static final class EnergyHandler implements IEnergyStorage {
  private final team.reborn.energy.api.EnergyStorage storage;public EnergyHandler(team.reborn.energy.api.EnergyStorage storage){this.storage=storage;}public int receiveEnergy(int amount,boolean simulate){try(var tx=Transaction.openOuter()){int n=cap(storage.insert(amount,tx));if(!simulate)tx.commit();return n;}}public int extractEnergy(int amount,boolean simulate){try(var tx=Transaction.openOuter()){int n=cap(storage.extract(amount,tx));if(!simulate)tx.commit();return n;}}public int getEnergyStored(){return cap(storage.getAmount());}public int getMaxEnergyStored(){return cap(storage.getCapacity());}public boolean canReceive(){return storage.supportsInsertion();}public boolean canExtract(){return storage.supportsExtraction();}
 }
}
